spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/spring-board
    username: sa
    password:
    driver-class-name: org.h2.Driver
    data: classpath:data.sql
    schema: classpath:schema.sql
  output:
    ansi:
      enabled: always

logging:
  level: org.springframework.jdbc.core.JdbcTemplate=debug

