ifndef::snippets[]
:snippets: ../../../build/generated-snippets
endif::[]
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 3
:sectlinks:
:operation-http-request-title: 요청 예시
:operation-http-response-title: 응답 예시
:operation-request-fields: 요청 필드
:operation-response-fields: 응답 필

[[resources]]
= Resources

[[resources-accounts]]
== User

[[resources-accounts-create]]
=== 회원 가입

[[resources-accounts-create-successful]]
==== 성공

operation::accounts/create[snippets='http-request,http-response,request-fields,response-fields']

[[resources-accounts-get]]
=== 회원 정보 보기

[[resources-accounts-get-successful]]
==== 성공

operation::accounts/get[snippets='http-request,http-response,response-fields']

[[resources-accounts-update]]
=== 회원 정보 수정

[[resources-accounts-update-successful]]
==== 성공

operation::accounts/update[snippets='http-request,http-response,request-fields']

[[resources-accounts-delete]]
=== 회원 탈퇴

[[resources-accounts-delete-successful]]
==== 성공

operation::accounts/delete[snippets='http-request,http-response']

[[resources-articles]]
== Article

[[resources-articles-create]]
=== 글 작성

==== 성공

operation::articles/create[snippets='http-request,http-response,request-fields,response-fields']

[[resources-articles-get-all]]
=== 글 목록

==== 성공

operation::articles/get-all[snippets='http-request,http-response']

[[resources-articles-get]]
=== 글 조회

==== 성공

operation::articles/get[snippets='http-request,http-response,response-fields']

[[resources-articles-update]]
=== 글 수정

==== 성공

operation::articles/update[snippets='http-request,http-response,request-fields']

[[resources-articles-delete]]
=== 글 삭제

==== 성공

operation::articles/delete[snippets='http-request,http-response']



